theme: jekyll-theme-hacker
title: "Eurotrip Flight & Planning Tracker"
description: "Live travel planning notes, logs, and updates"


url: "https://truedevopsmk-lab.github.io"
baseurl: "/Flight_Tracker_Eurotripv5"

permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

defaults:
  - scope:
      path: "BLR-BUD-BER-BLR"
    values:
      layout: trip_layout
  - scope:
      path: "Travel-Log"
    values:
      layout: log_layout
  - scope:
      path: "flights"
    values:
      layout: flight_layout
  - scope:
      path: "gallery"
    values:
      layout: gallery_layout
  - scope:
      path: "timeline"
    values:
      layout: timeline_layout
  - scope:
      path: "expenses"
    values:
      layout: expenses_layout
