
theme: jekyll-theme-time-machine
baseurl: "/Flight_Tracker_Eurotripv5"
url: "https://truedevopsmk-lab.github.io"

permalink: pretty

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "BLR-BUD-BER-BLR"
    values:
      layout: trip_layout
  - scope:
      path: "Travel-Log"
    values:
      layout: log_layout
  - scope:
      path: "flights"
    values:
      layout: flight_layout
  - scope:
      path: "gallery"
    values:
      layout: gallery_layout
  - scope:
      path: "timeline"
    values:
      layout: timeline_layout
  - scope:
      path: "expenses"
    values:
      layout: expenses_layout
